// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion_Parking.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestion_Parking.Models.Emploi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Groupeid")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("Groupeid");

                    b.ToTable("Emplois");
                });

            modelBuilder.Entity("Gestion_Parking.Models.Groupe", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Groupes");
                });

            modelBuilder.Entity("Gestion_Parking.Models.Personne", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("motdepasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Personnes");

                    b.HasDiscriminator().HasValue("Personne");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Gestion_Parking.Models.PlaceParking", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("etat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("PlaceParkings");
                });

            modelBuilder.Entity("Gestion_Parking.Models.Reservation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<int>("etudiant_id")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("heureDebut")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("heureFin")
                        .HasColumnType("time");

                    b.Property<string>("lieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("personnel_id")
                        .HasColumnType("int");

                    b.Property<int>("placeParking_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("etudiant_id");

                    b.HasIndex("personnel_id");

                    b.HasIndex("placeParking_id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Gestion_Parking.Models.Admin", b =>
                {
                    b.HasBaseType("Gestion_Parking.Models.Personne");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("Gestion_Parking.Models.Etudiant", b =>
                {
                    b.HasBaseType("Gestion_Parking.Models.Personne");

                    b.Property<string>("Groupeid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("groupe_id")
                        .HasColumnType("int");

                    b.HasIndex("Groupeid");

                    b.HasDiscriminator().HasValue("Etudiant");
                });

            modelBuilder.Entity("Gestion_Parking.Models.Personnel", b =>
                {
                    b.HasBaseType("Gestion_Parking.Models.Personne");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Personnel");
                });

            modelBuilder.Entity("Gestion_Parking.Models.Emploi", b =>
                {
                    b.HasOne("Gestion_Parking.Models.Groupe", "Groupe")
                        .WithMany()
                        .HasForeignKey("Groupeid");

                    b.Navigation("Groupe");
                });

            modelBuilder.Entity("Gestion_Parking.Models.Reservation", b =>
                {
                    b.HasOne("Gestion_Parking.Models.Etudiant", "Etudiant")
                        .WithMany("Reservations")
                        .HasForeignKey("etudiant_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion_Parking.Models.Personnel", "Personnel")
                        .WithMany("Reservations")
                        .HasForeignKey("personnel_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion_Parking.Models.PlaceParking", "PlaceParking")
                        .WithMany("Reservations")
                        .HasForeignKey("placeParking_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Etudiant");

                    b.Navigation("Personnel");

                    b.Navigation("PlaceParking");
                });

            modelBuilder.Entity("Gestion_Parking.Models.Etudiant", b =>
                {
                    b.HasOne("Gestion_Parking.Models.Groupe", "Groupe")
                        .WithMany()
                        .HasForeignKey("Groupeid");

                    b.Navigation("Groupe");
                });

            modelBuilder.Entity("Gestion_Parking.Models.PlaceParking", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Gestion_Parking.Models.Etudiant", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Gestion_Parking.Models.Personnel", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
